### ISSUE TITLE
Error restarting trials when using R script wrapper 

### ISSUE THREAD

**Issue by jemissik** [madeline-scyphers/boa#66]
Using the example r script lite wrapper, after using the restart feature the scheduler just keeps waiting for completed trials. The correct trial status file, etc gets written, but boa isn't reading it somehow. 

Should also add a test for the r wrappers that tests the restart feature.

**Comment by madeline-scyphers** [comment]
@madeline-scyphers Check if this is fixed with new versions of Ax.

**Comment by madeline-scyphers** [comment]
Fixed with 74ed31e
