### ISSUE TITLE
Add documentation about using mamba solver

### ISSUE THREAD

**Issue by jemissik** [madeline-scyphers/boa#81]
We should reconsider which installation we should recommend as the preferred option. Probably either miniconda or mambaforge should be recommended as the preferred choice. Anaconda seems to be more prone to issues because it has so many packages (and requires a lot of unnecessary stuff to be downloaded). Mambaforge installer seems to have much better performance and all of out CI jobs use mamba. The only issue is that mambaforge is less "official" than miniconda/anaconda, and tends to get a lot of security warnings for downloading/installing on windows.

**Comment by madeline-scyphers** [comment]
I don't know if this is necessary anymore since libmamba is now the default solver. Miniconda might be a better recommendation, but I am ok with leaving it up to the user and not specifying.
